# Values used for the deployed application.
replicaCount: 2
service:
  name: native-ingester-cms
env:
  QUEUE_READ_GROUP: "nativeIngesterCms"
  QUEUE_READ_TOPIC: "PreNativeCmsPublicationEvents"
  NATIVE_CONTENT_UUID_FIELDS: "uuid,post.uuid,data.uuidv3,id"
  CONFIG: "config.json"
  QUEUE_WRITE_TOPIC: "NativeCmsPublicationEvents"
  PANIC_GUIDE_URL: "https://runbooks.in.ft.com/native-ingester"
resources:
  requests:
    memory: 250Mi
  limits:
    memory: 512Mi
